services:
  - type: web
    name: task-management-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import create_app; from app.models import db; app = create_app(); app.app_context().push(); db.create_all()"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString

databases:
  - name: task-management-db
    databaseName: taskmanagement
    plan: free
    ipAllowList: []  # allow all IPs
